name: Update Timetable
on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight (UTC)
  workflow_dispatch: # Allow manual trigger from GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install requests beautifulsoup4
        
      - name: Fetch Timetable
        env:
          PROGRAM: ${{ vars.PROGRAM }}
          SECTION: ${{ vars.SECTION }}
          SEMESTER: ${{ vars.SEMESTER }}
        run: python fetch_timetable.py
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    permissions:
      pages: write
      id-token: write
